name: AkiraCore
version: 1.2.1
main: com.akira.core.AkiraCore
authors: [Yukino_Akira]
api-version: 1.20

commands:
  akiracore:
    permission: akiracore.user

permissions:
  akiracore.user:
    default: true
  akiracore.admin:
    default: op